import 'package:get/get.dart';

class MyLocalizations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "app_name": "Virtual Origen",
          "first_time_first_body":
              "Welcome to Virtual Origen, the app that will help you manage your decentralized home.",
          "first_time_second_body":
              "Manage your home resources efficiently and sustainably.",
          "first_time_third_body":
              "Manage your devices from anywhere in a smart and domotized way.",
          "next": "Next",
          "get_started": "Get Started!",
          "login_with_google_success": "Login with Google successful",
          "login_with_email_success": "Login with email successful",
          "singup_with_email_success": "Sing up with email successful",
          "email_verified": "Email verified",
          "email_verified_sent": "Email verification sent",
          "email_recovery_sent": "Email recovery sent",
          "title_singup": "Sing up",
          "login_with_google": "Login with Google",
          "email": "Email",
          "password": "Password",
          "password_confirm": "Confirm password",
          "singup": "Sing up",
          "have_account": "Already have an account?",
          "login_button": "Login",
          "title_login": "Login",
          "login": "Login",
          "no_account": "Don't have an account?",
          "singup_button": "Sing up",
          "forgot_password": "Forgot your password?",
          "title_forgot_password": "Recover password",
          "send_email_password": "Send recovery email",
          "title_email_validate": "Validate email",
          "email_validate":
              "Access your email inbox and validate your account to continue.",
          "check_email": "Check your email validation manually",
          "resend_email": "Resend validation email",
          "or": "or",
          "welcome": "Hi, {user}!",
          "property_name": "Property name",
          "save": "Save",
          "cancel": "Cancel",
          "delete": "Delete",
          "property": "Properties",
          "devices": "Devices: {devices}",
          "guests": "Guests: {guests}",
          "day_1": "MO",
          "day_2": "TU",
          "day_3": "WE",
          "day_4": "TH",
          "day_5": "FR",
          "day_6": "SA",
          "day_7": "SU",
          "day_long_1": "Monday",
          "day_long_2": "Tuesday",
          "day_long_3": "Wednesday",
          "day_long_4": "Thursday",
          "day_long_5": "Friday",
          "day_long_6": "Saturday",
          "day_long_7": "Sunday",
          "properties": "Properties",
          "smart_devices": "Smart devices",
          "smart_device_name": "Device name",
          "time_zones": "Time zones",
          "battery_range_title": "Battery range (%)",
          "battery_range_reason":
              "Battery percentage range that marks when the device can be activated.",
          "production_range_title": "Production range (W)",
          "production_range_reason":
              "Energy production range (Watts) that marks when the device can be activated.",
          "consumption_range_title": "Consumption range (W)",
          "consumption_range_reason":
              "Energy consumption range (Watts) that marks when the device can be activated.",
          "temperature_range_title": "Temperature range (ºC)",
          "temperature_range_reason":
              "Temperature range (ºC) that marks when the device can be activated.",
          "rain_range_title": "Rain range (%)",
          "rain_range_reason":
              "Rain percentage range that marks when the device can be activated.",
          "manual_mode": "Manual mode, skip restrictions.",
          "smart_device_on": "On",
          "smart_device_off": "Off",
          "new_smart_device": "New smart device",
          "edit_smart_device": "Edit smart device",
          "new_property": "New property",
          "edit_property": "Edit property",
          "chart_inversor_title": "Inversor",
          "chart_time_title": "Time (dd HH:mm)",
          "battery_title": "Battery",
          "gain_title": "Production",
          "consumption_title": "Consumption",
          "consumption_reason": "Real-time energy consumption (Watts).",
          "gain_reason": "Real-time energy production (Watts).",
          "chart_weather_title": "Weather",
          "temperature_title": "Temperature",
          "rain_title": "Rain",
          "wind_title": "Wind",
          "chart_battery_title": "Battery (%)",
          "guest_title": "Guests",
          "add_guest": "Add guest",
          "send_invitation_title": "Send invitation",
          "guest_email": "Guest email",
          "read": "Read",
          "write": "Write",
          "full": "Full",
          "send": "Send",
          "invitation_sent": "Invitation sent",
          "invitation_not_sent": "Invitation not sent",
          "invitation_already_sent": "Invitation already sent",
          "invitation_yourself": "You can't invite yourself :)",
          "guest_permission_changed": "Guest permission changed",
          "guest_permission_not_changed": "Guest permission not changed",
          "scene_saved": "Scene saved",
          "scene_not_saved": "Scene not saved",
          "no_smart_devices": "No smart devices",
          "smart_device_invalid": "Invalid smart device",
          "smart_device_saved": "Smart device saved",
          "smart_device_not_saved": "Smart device not saved",
          "apply_scene": "Apply scene",
          "apply_scene_message":
              "Do you want to apply the scene? This will erase the current configuration.",
          "apply": "Apply",
          "scene_applied": "Scene applied",
          "properties_shared": "Shared properties",
          "scene_title": "Scenes",
          "add_scene": "Add scene",
          "add_scene_device": "Add device to scene",
          "new_scene_title": "New scene",
          "edit_scene_title": "Edit scene",
          "scene_name": "Scene name",
          "light": "Light",
          "boiler": "Boiler",
          "air_conditioner": "Air conditioner",
          "irrigation": "Irrigation",
          "other": "Other",
          "add_property": "Add property",
          "user_data": "User data",
          "user_name": "User name",
          "new_invitations": "New invitations",
          "invitations": "Invitations",
          "add_smart_device": "Add smart device",
          "change_language": "Change language",
          "change_theme": "Change theme",
          "sign_out": "Sign out",
        },
        'es_ES': {
          "app_name": "Virtual Origen",
          "first_time_first_body":
              "Bienvenido a Virtual Origen, la aplicación que te ayudará a gestionar tu hogar descentralizado.",
          "first_time_second_body":
              "Gestiona los recursos de tu hogar de manera eficiente y sostenible.",
          "first_time_third_body":
              "Gestiona tus dispositivos desde cualquier lugar de manera inteligente y domotizada.",
          "next": "Siguiente",
          "get_started": "¡Vamos a empezar!",
          "login_with_google_success": "Inicio de sesión con Google exitoso",
          "login_with_email_success":
              "Inicio de sesión con correo electrónico exitoso",
          "singup_with_email_success":
              "Registro con correo electrónico exitoso",
          "email_verified": "Correo verificado",
          "email_verified_sent": "Correo de verificación enviado",
          "email_recovery_sent": "Correo de recuperación enviado",
          "title_singup": "Registro",
          "login_with_google": "Iniciar sesión con Google",
          "email": "Correo electrónico",
          "password": "Contraseña",
          "password_confirm": "Confirmar contraseña",
          "singup": "Registrarse",
          "have_account": "¿Ya tienes una cuenta?",
          "login_button": "Iniciar sesión",
          "title_login": "Iniciar sesión",
          "login": "Iniciar sesión",
          "no_account": "¿No tienes una cuenta?",
          "singup_button": "Registrarse",
          "forgot_password": "¿Olvidaste tu contraseña?",
          "title_forgot_password": "Recuperar contraseña",
          "send_email_password": "Enviar correo de recuperación",
          "title_email_validate": "Validar correo",
          "email_validate":
              "Accede a la bandeja de entrada de tu correo y valida tu cuenta para continuar.",
          "check_email": "Revisa la validación de tu correo manualmente",
          "resend_email": "Reenviar correo de validación",
          "or": "o",
          "welcome": "¡Hola, {user}!",
          "property_name": "Nombre de la propiedad",
          "save": "Guardar",
          "cancel": "Cancelar",
          "delete": "Eliminar",
          "property": "Propiedades",
          "devices": "Dispositivos: {devices}",
          "guests": "Invitados: {guests}",
          "day_1": "LU",
          "day_2": "MA",
          "day_3": "X",
          "day_4": "JU",
          "day_5": "VI",
          "day_6": "SA",
          "day_7": "DO",
          "day_long_1": "Lunes",
          "day_long_2": "Martes",
          "day_long_3": "Miércoles",
          "day_long_4": "Jueves",
          "day_long_5": "Viernes",
          "day_long_6": "Sábado",
          "day_long_7": "Domingo",
          "properties": "Propiedades",
          "smart_devices": "Dispositivos inteligentes",
          "smart_device_name": "Nombre del dispositivo",
          "time_zones": "Zonas horarias",
          "battery_range_title": "Rango de batería (%)",
          "battery_range_reason":
              "Rango de porcentaje de batería que marca cuando se podra activar el dispositivo.",
          "production_range_title": "Rango de producción (W)",
          "production_range_reason":
              "Rango de producción de energía (Watios) que marca cuando se podra activar el dispositivo.",
          "consumption_range_title": "Rango de consumo (W)",
          "consumption_range_reason":
              "Rango de consumo de energía (Watios) que marca cuando se podra activar el dispositivo.",
          "temperature_range_title": "Rango de temperatura (ºC)",
          "temperature_range_reason":
              "Rango de temperatura (ºC) que marca cuando se podra activar el dispositivo.",
          "rain_range_title": "Rango de lluvia (%)",
          "rain_range_reason":
              "Rango de porcentaje de lluvia que marca cuando se podra activar el dispositivo.",
          "manual_mode": "Modo manual, se salta las restricciones.",
          "smart_device_on": "Activado",
          "smart_device_off": "Desactivado",
          "new_smart_device": "Nuevo dispositivo inteligente",
          "edit_smart_device": "Editar dispositivo inteligente",
          "new_property": "Nueva propiedad",
          "edit_property": "Editar propiedad",
          "chart_inversor_title": "Inversor",
          "chart_time_title": "Tiempo (dd HH:mm)",
          "battery_title": "Batería",
          "gain_title": "Producción",
          "consumption_title": "Consumo",
          "consumption_reason": "Consumo de energía en tiempo real (Watios).",
          "gain_reason": "Producción de energía en tiempo real (Watios).",
          "chart_weather_title": "Tiempo",
          "temperature_title": "Temperatura",
          "rain_title": "Lluvia",
          "wind_title": "Viento",
          "chart_battery_title": "Batería (%)",
          "guest_title": "Invitados",
          "add_guest": "Añadir invitado",
          "send_invitation_title": "Enviar invitación",
          "guest_email": "Correo del invitado",
          "read": "Lectura",
          "write": "Escritura",
          "full": "Completo",
          "send": "Enviar",
          "invitation_sent": "Invitación enviada",
          "invitation_not_sent": "Invitación no enviada",
          "invitation_already_sent": "Invitación ya enviada",
          "invitation_yourself": "No puedes invitarte a ti mismo :)",
          "guest_permission_changed": "Permiso de invitado cambiado",
          "guest_permission_not_changed": "Permiso de invitado no cambiado",
          "scene_saved": "Escena guardada",
          "scene_not_saved": "Escena no guardada",
          "no_smart_devices": "No hay dispositivos inteligentes",
          "smart_device_invalid": "Dispositivo inteligente inválido",
          "smart_device_saved": "Dispositivo inteligente guardado",
          "smart_device_not_saved": "Dispositivo inteligente no guardado",
          "apply_scene": "Aplicar escena",
          "apply_scene_message":
              "¿Quieres aplicar la escena? Esto borrará la configuración actual.",
          "apply": "Aplicar",
          "scene_applied": "Escena aplicada",
          "properties_shared": "Propiedades compartidas",
          "scene_title": "Escenas",
          "add_scene": "Añadir escena",
          "add_scene_device": "Añadir dispositivo a la escena",
          "new_scene_title": "Nueva escena",
          "edit_scene_title": "Editar escena",
          "scene_name": "Nombre de la escena",
          "light": "Luz",
          "boiler": "Caldera",
          "air_conditioner": "Aire acondicionado",
          "irrigation": "Riego",
          "other": "Otro",
          "add_property": "Añadir propiedad",
          "user_data": "Datos de usuario",
          "user_name": "Nombre de usuario",
          "new_invitations": "Nuevas invitaciones",
          "invitations": "Invitaciones",
          "add_smart_device": "Añadir dispositivo inteligente",
          "change_language": "Cambiar idioma",
          "change_theme": "Cambiar tema",
          "sign_out": "Cerrar sesión",
        },
      };
}
