import 'package:get/get.dart';

class MyLocalizations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "app_name": "Virtual Origen",
          "first_time_first_body":
              "Welcome to Virtual Origen, the app that will help you manage your decentralized home.",
          "first_time_second_body":
              "Manage your home resources efficiently and sustainably.",
          "first_time_third_body":
              "Manage your devices from anywhere in a smart and domotized way.",
          "next": "Next",
          "get_started": "Get Started!",
          "login_with_google_success": "Login with Google successful",
          "login_with_email_success": "Login with email successful",
          "singup_with_email_success": "Sing up with email successful",
          "email_verified": "Email verified",
          "email_verified_sent": "Email verification sent",
          "email_recovery_sent": "Email recovery sent",
          "title_singup": "Sing up",
          "login_with_google": "Login with Google",
          "email": "Email",
          "password": "Password",
          "password_confirm": "Confirm password",
          "singup": "Sing up",
          "have_account": "Already have an account?",
          "login_button": "Login",
          "title_login": "Login",
          "login": "Login",
          "no_account": "Don't have an account?",
          "singup_button": "Sing up",
          "forgot_password": "Forgot your password?",
          "title_forgot_password": "Recover password",
          "send_email_password": "Send recovery email",
          "title_email_validate": "Validate email",
          "email_validate":
              "Access your email inbox and validate your account to continue.",
          "check_email": "Check your email validation manually",
          "resend_email": "Resend validation email",
          "or": "or",
          "welcome": "Hi, {user}!",
          "property_name": "Property name",
          "save": "Save",
          "cancel": "Cancel",
          "delete": "Delete",
          "property": "Properties",
          "devices": "Devices: {devices}",
          "guests": "Guests: {guests}",
          "day_1": "MO",
          "day_2": "TU",
          "day_3": "WE",
          "day_4": "TH",
          "day_5": "FR",
          "day_6": "SA",
          "day_7": "SU",
          "day_long_1": "Monday",
          "day_long_2": "Tuesday",
          "day_long_3": "Wednesday",
          "day_long_4": "Thursday",
          "day_long_5": "Friday",
          "day_long_6": "Saturday",
          "day_long_7": "Sunday",
          "properties": "Properties",
          "smart_devices": "Smart devices",
          "smart_device_name": "Device name",
          "time_zones": "Time zones",
          "battery_range_title": "Battery range (%)",
          "battery_range_reason":
              "Battery percentage range that marks when the device can be activated.",
          "production_range_title": "Production range (W)",
          "production_range_reason":
              "Energy production range (Watts) that marks when the device can be activated.",
          "consumption_range_title": "Consumption range (W)",
          "consumption_range_reason":
              "Energy consumption range (Watts) that marks when the device can be activated.",
          "temperature_range_title": "Temperature range (ºC)",
          "temperature_range_reason":
              "Temperature range (ºC) that marks when the device can be activated.",
          "rain_range_title": "Rain range (%)",
          "rain_range_reason":
              "Rain percentage range that marks when the device can be activated.",
          "manual_mode": "Manual mode, skip restrictions.",
          "smart_device_on": "On",
          "smart_device_off": "Off",
        },
        'es_ES': {
          "app_name": "Virtual Origen",
          "first_time_first_body":
              "Bienvenido a Virtual Origen, la aplicación que te ayudará a gestionar tu hogar descentralizado.",
          "first_time_second_body":
              "Gestiona los recursos de tu hogar de manera eficiente y sostenible.",
          "first_time_third_body":
              "Gestiona tus dispositivos desde cualquier lugar de manera inteligente y domotizada.",
          "next": "Siguiente",
          "get_started": "¡Vamos a empezar!",
          "login_with_google_success": "Inicio de sesión con Google exitoso",
          "login_with_email_success":
              "Inicio de sesión con correo electrónico exitoso",
          "singup_with_email_success":
              "Registro con correo electrónico exitoso",
          "email_verified": "Correo verificado",
          "email_verified_sent": "Correo de verificación enviado",
          "email_recovery_sent": "Correo de recuperación enviado",
          "title_singup": "Registro",
          "login_with_google": "Iniciar sesión con Google",
          "email": "Correo electrónico",
          "password": "Contraseña",
          "password_confirm": "Confirmar contraseña",
          "singup": "Registrarse",
          "have_account": "¿Ya tienes una cuenta?",
          "login_button": "Iniciar sesión",
          "title_login": "Iniciar sesión",
          "login": "Iniciar sesión",
          "no_account": "¿No tienes una cuenta?",
          "singup_button": "Registrarse",
          "forgot_password": "¿Olvidaste tu contraseña?",
          "title_forgot_password": "Recuperar contraseña",
          "send_email_password": "Enviar correo de recuperación",
          "title_email_validate": "Validar correo",
          "email_validate":
              "Accede a la bandeja de entrada de tu correo y valida tu cuenta para continuar.",
          "check_email": "Revisa la validación de tu correo manualmente",
          "resend_email": "Reenviar correo de validación",
          "or": "o",
          "welcome": "¡Hola, {user}!",
          "property_name": "Nombre de la propiedad",
          "save": "Guardar",
          "cancel": "Cancelar",
          "delete": "Eliminar",
          "property": "Propiedades",
          "devices": "Dispositivos: {devices}",
          "guests": "Invitados: {guests}",
          "day_1": "LU",
          "day_2": "MA",
          "day_3": "X",
          "day_4": "JU",
          "day_5": "VI",
          "day_6": "SA",
          "day_7": "DO",
          "day_long_1": "Lunes",
          "day_long_2": "Martes",
          "day_long_3": "Miércoles",
          "day_long_4": "Jueves",
          "day_long_5": "Viernes",
          "day_long_6": "Sábado",
          "day_long_7": "Domingo",
          "properties": "Propiedades",
          "smart_devices": "Dispositivos inteligentes",
          "smart_device_name": "Nombre del dispositivo",
          "time_zones": "Zonas horarias",
          "battery_range_title": "Rango de batería (%)",
          "battery_range_reason":
              "Rango de porcentaje de batería que marca cuando se podra activar el dispositivo.",
          "production_range_title": "Rango de producción (W)",
          "production_range_reason":
              "Rango de producción de energía (Watios) que marca cuando se podra activar el dispositivo.",
          "consumption_range_title": "Rango de consumo (W)",
          "consumption_range_reason":
              "Rango de consumo de energía (Watios) que marca cuando se podra activar el dispositivo.",
          "temperature_range_title": "Rango de temperatura (ºC)",
          "temperature_range_reason":
              "Rango de temperatura (ºC) que marca cuando se podra activar el dispositivo.",
          "rain_range_title": "Rango de lluvia (%)",
          "rain_range_reason":
              "Rango de porcentaje de lluvia que marca cuando se podra activar el dispositivo.",
          "manual_mode": "Modo manual, se salta las restricciones.",
          "smart_device_on": "Activado",
          "smart_device_off": "Desactivado",
        },
      };
}
